[project]
name = "nces-data-tools"
version = "0.1.0"
description = "Tools for working with downloaded NCES school data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "click>=8.1.7",
    "httpx>=0.27.2",
    "ruff>=0.7.0",
]
